let mode = 'login', selectedTemplate = 'Portföy', dashboardSites = [];
const configured = () => window.KUR_CONFIG && !window.KUR_CONFIG.supabaseUrl.startsWith('SUPABASE_');
const db = () => window.supabase.createClient(KUR_CONFIG.supabaseUrl, KUR_CONFIG.supabaseAnonKey);
function showAuth(next) { mode = next; document.querySelector('#authModal').classList.remove('hidden'); renderAuth(); }
function hideAuth() { document.querySelector('#authModal').classList.add('hidden'); }
function toggleAuth() { mode = mode === 'login' ? 'signup' : 'login'; renderAuth(); }
function renderAuth() { const sign = mode === 'signup'; document.querySelector('#authTitle').textContent = sign ? 'Hemen başla' : 'Hoş geldin'; document.querySelector('#authHelp').textContent = sign ? 'İlk siteni birkaç dakika içinde oluştur.' : 'Paneline erişmek için giriş yap.'; document.querySelector('#authSubmit').textContent = sign ? 'Ücretsiz hesap oluştur' : 'Giriş yap'; document.querySelector('#switchText').textContent = sign ? 'Zaten hesabın var mı? ' : 'Hesabın yok mu? '; document.querySelector('#switchAuth').textContent = sign ? 'Giriş yap' : 'Ücretsiz kayıt ol'; document.querySelector('#authMessage').textContent = ''; }
async function submitAuth(e) { e.preventDefault(); if (!configured()) return showMessage('Canlı üyelik için önce config.js dosyasına Supabase bilgilerini ekleyin.'); const email = document.querySelector('#email').value, password = document.querySelector('#password').value; const { error } = mode === 'signup' ? await db().auth.signUp({ email, password }) : await db().auth.signInWithPassword({ email, password }); if (error) return showMessage(error.message); if (mode === 'signup') showMessage('Onay e-postanı kontrol et; ardından giriş yap.'); else boot(); }
function showMessage(x) { document.querySelector('#authMessage').textContent = x; }
function setupDashboard(email) { document.querySelector('.side').innerHTML = `<div class="logo">kur<i></i></div><a class="active" data-view="sites" onclick="showView('sites')">▦ Sitelerim</a><a data-view="stats" onclick="showView('stats')">◉ İstatistikler</a><a data-view="templates" onclick="showView('templates')">▣ Hazır şablonlar</a><a data-view="settings" onclick="showView('settings')">⚙ Ayarlar</a><div class="account-menu"><button class="account-button" onclick="toggleUserMenu()"><span class="avatar">${escapeHTML(email[0].toUpperCase())}</span><span>${escapeHTML(email)}</span><b>⌄</b></button><div id="userMenu" class="user-popup hidden"><b>Hesabım</b><small>${escapeHTML(email)}</small><button onclick="showView('settings')">Hesap ayarları</button><button onclick="signOut()">Çıkış yap</button></div></div>`; document.querySelector('.dash-main').innerHTML = `<section class="dash-view" id="view-sites"><div class="dash-top"><div><h1>Sitelerin</h1><p>Fikirlerini dünyayla paylaşmaya devam et.</p></div><button class="primary" onclick="showNewSite()">＋ Yeni site oluştur</button></div><div class="site-grid" id="sites"></div></section><section class="dash-view hidden" id="view-stats"><div class="dash-top"><div><h1>İstatistikler</h1><p>Sitelerinin kısa özeti.</p></div></div><div class="stats-grid" id="stats"></div><div class="chart-card"><h3>Son 7 gün</h3><div class="bars"><i style="height:34%"></i><i style="height:54%"></i><i style="height:42%"></i><i style="height:72%"></i><i style="height:46%"></i><i style="height:83%"></i><i style="height:63%"></i></div><div class="week"><span>Pzt</span><span>Sal</span><span>Çar</span><span>Per</span><span>Cum</span><span>Cmt</span><span>Paz</span></div></div></section><section class="dash-view hidden" id="view-templates"><div class="dash-top"><div><h1>Hazır şablonlar</h1><p>Birini seç, kendi içeriğinle kişiselleştir.</p></div></div><div class="template-gallery"><button class="gallery-card coral" onclick="newWithTemplate('Portföy')"><span class="mini-site-title">Yaptığın iş<br>görünür olsun.</span><small>Portföy</small><b>Bu şablonu kullan →</b></button><button class="gallery-card night" onclick="newWithTemplate('İşletme')"><span class="mini-site-title">Lezzet burada<br>başlar.</span><small>İşletme</small><b>Bu şablonu kullan →</b></button><button class="gallery-card violet" onclick="newWithTemplate('Blog')"><span class="mini-site-title">Basit. Güçlü.<br>Senin.</span><small>Blog</small><b>Bu şablonu kullan →</b></button><button class="gallery-card green" onclick="newWithTemplate('Mağaza')"><span class="mini-site-title">Yeni sezon<br>burada.</span><small>Mağaza</small><b>Bu şablonu kullan →</b></button></div></section><section class="dash-view hidden" id="view-settings"><div class="settings-card"><h1>Hesap ayarları</h1><p>Hesabınla ilgili temel bilgiler.</p><label>E-posta adresi</label><div class="email-display">${escapeHTML(email)}</div><button class="ghost" onclick="signOut()">Çıkış yap</button></div></section>`; }
async function boot() { if (!configured()) return; const { data: { user } } = await db().auth.getUser(); if (!user) return; hideAuth(); document.querySelector('#marketing').classList.add('hidden'); document.querySelector('#dashboard').classList.remove('hidden'); setupDashboard(user.email); const { data, error } = await db().from('sites').select('*').order('created_at', { ascending: false }); if (!error) { dashboardSites = data; renderSites(data); renderStats(data); } }
function showView(name) { document.querySelectorAll('.dash-view').forEach(x => x.classList.add('hidden')); document.querySelector(`#view-${name}`).classList.remove('hidden'); document.querySelectorAll('.side a[data-view]').forEach(x => x.classList.toggle('active', x.dataset.view === name)); document.querySelector('#userMenu')?.classList.add('hidden'); }
function renderSites(items) { const area = document.querySelector('#sites'); if (!items.length) { area.innerHTML = '<div class="empty"><b>Henüz bir siten yok.</b><br><br>İlk siteni oluşturarak başlayalım.</div>'; return; } area.innerHTML = items.map(x => `<article class="site-card"><div class="site-shot"><div class="shot-title">${escapeHTML(x.name)}</div></div><div class="site-info"><b>${escapeHTML(x.name)}</b><small>${x.template} · ${x.published ? 'Yayında' : 'Taslak'}</small><div class="site-actions"><button class="primary" onclick="editSite('${x.id}')">Düzenle</button><button class="ghost" onclick="editSite('${x.id}')">Önizle</button></div></div></article>`).join(''); }
function renderStats(items) { const total = items.length, live = items.filter(x => x.published).length, draft = total - live; document.querySelector('#stats').innerHTML = `<article><span>Toplam siteler</span><b>${total}</b><small>Hesabındaki tüm siteler</small></article><article><span>Yayındaki siteler</span><b>${live}</b><small>Herkese açık sitelerin</small></article><article><span>Taslaklar</span><b>${draft}</b><small>Düzenlemeye hazır siteler</small></article>`; }
function editSite(id) { location.href = `editor.html?id=${encodeURIComponent(id)}`; }
function showNewSite() { document.querySelector('#newModal').classList.remove('hidden'); }
function hideNewSite() { document.querySelector('#newModal').classList.add('hidden'); }
function newWithTemplate(type) { selectedTemplate = type; document.querySelectorAll('.template').forEach(x => x.classList.toggle('selected', x.dataset.template === type)); showNewSite(); }
function pickTemplate(el) { document.querySelectorAll('.template').forEach(x => x.classList.remove('selected')); el.classList.add('selected'); selectedTemplate = el.dataset.template; }
async function createSite(e) { e.preventDefault(); if (!configured()) return; const name = document.querySelector('#siteName').value.trim(); const content = { headline: name, subtitle: 'Kendini ve işini dünyaya anlat.', button: 'Keşfet', accent: '#d6ff4d', blocks: [] }; const { error } = await db().from('sites').insert({ name, template: selectedTemplate, content }); if (error) return alert(error.message); hideNewSite(); e.target.reset(); boot(); }
function toggleUserMenu() { document.querySelector('#userMenu').classList.toggle('hidden'); }
async function signOut() { await db().auth.signOut(); location.href = 'index.html'; }
function escapeHTML(v) { const d = document.createElement('div'); d.textContent = v; return d.innerHTML; }
const extraStyle = document.createElement('style'); extraStyle.textContent = `.dash-view{width:100%}.account-menu{position:absolute;bottom:24px;left:18px;right:18px}.account-button{width:100%;display:flex;gap:8px;align-items:center;background:#f5f7f5;border-radius:9px;padding:10px;color:#43535d;font-size:12px;text-align:left}.account-button span:nth-child(2){overflow:hidden;text-overflow:ellipsis}.account-button b{margin-left:auto}.avatar{display:grid;place-items:center;width:24px;height:24px;border-radius:50%;background:#d6ff4d;color:#17232d}.user-popup{position:absolute;bottom:48px;background:#fff;border:1px solid var(--line);box-shadow:0 8px 24px rgba(27,43,37,.15);width:100%;border-radius:9px;padding:10px}.user-popup b,.user-popup small{display:block;padding:3px 5px}.user-popup small{color:var(--muted);overflow:hidden;text-overflow:ellipsis}.user-popup button{display:block;width:100%;text-align:left;padding:9px 5px;background:transparent;color:var(--ink);margin-top:4px}.stats-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin:30px 0}.stats-grid article,.chart-card,.settings-card{background:#fff;border:1px solid var(--line);border-radius:13px;padding:22px}.stats-grid span,.stats-grid small{display:block;color:var(--muted);font-size:13px}.stats-grid b{font-size:40px;letter-spacing:-2px;margin:12px 0;display:block}.chart-card{max-width:680px}.chart-card h3{margin:0 0 20px}.bars{height:165px;display:flex;align-items:end;gap:16px;border-bottom:1px solid var(--line);padding:0 14px}.bars i{flex:1;background:var(--purple);border-radius:6px 6px 0 0}.week{display:flex;justify-content:space-between;color:var(--muted);font-size:11px;padding:10px 13px}.template-gallery{display:grid;grid-template-columns:repeat(2,minmax(220px,1fr));gap:16px;margin-top:30px}.gallery-card{text-align:left;border:1px solid var(--line);border-radius:13px;min-height:230px;padding:22px;display:flex;flex-direction:column;background:#fff;color:var(--ink)}.gallery-card:hover{transform:translateY(-3px);box-shadow:0 10px 21px rgba(23,36,46,.1)}.gallery-card small{font-size:12px;font-weight:800;margin-top:auto}.gallery-card b{margin-top:8px;font-size:13px}.mini-site-title{font-size:27px;line-height:.95;letter-spacing:-1.5px;font-weight:950}.coral{background:#ffd7c2}.night{background:#192631;color:#fff}.violet{background:#e6defe}.green{background:#e5f4e5}.settings-card{max-width:560px;margin-top:25px}.settings-card h1{margin:0}.settings-card p{color:var(--muted)}.settings-card label{font-size:12px;font-weight:800;display:block;margin-top:26px}.email-display{padding:12px;background:#f4f6f4;border-radius:7px;margin:8px 0 20px}@media(max-width:720px){.stats-grid,.template-gallery{grid-template-columns:1fr}.account-menu{display:none}}`; document.head.append(extraStyle);
if (configured()) boot();
