let mode = 'login', selectedTemplate = 'Portföy';
const configured = () => window.KUR_CONFIG && !window.KUR_CONFIG.supabaseUrl.startsWith('SUPABASE_');
const db = () => window.supabase.createClient(KUR_CONFIG.supabaseUrl, KUR_CONFIG.supabaseAnonKey);
function showAuth(next) { mode = next; document.querySelector('#authModal').classList.remove('hidden'); renderAuth(); }
function hideAuth() { document.querySelector('#authModal').classList.add('hidden'); }
function toggleAuth() { mode = mode === 'login' ? 'signup' : 'login'; renderAuth(); }
function renderAuth() { const sign = mode === 'signup'; document.querySelector('#authTitle').textContent = sign ? 'Hemen başla' : 'Hoş geldin'; document.querySelector('#authHelp').textContent = sign ? 'İlk siteni birkaç dakika içinde oluştur.' : 'Paneline erişmek için giriş yap.'; document.querySelector('#authSubmit').textContent = sign ? 'Ücretsiz hesap oluştur' : 'Giriş yap'; document.querySelector('#switchText').textContent = sign ? 'Zaten hesabın var mı? ' : 'Hesabın yok mu? '; document.querySelector('#switchAuth').textContent = sign ? 'Giriş yap' : 'Ücretsiz kayıt ol'; document.querySelector('#authMessage').textContent = ''; }
async function submitAuth(e) { e.preventDefault(); if (!configured()) return showMessage('Canlı üyelik için önce config.js dosyasına Supabase bilgilerini ekleyin.'); const email = document.querySelector('#email').value, password = document.querySelector('#password').value; const { error } = mode === 'signup' ? await db().auth.signUp({ email, password }) : await db().auth.signInWithPassword({ email, password }); if (error) return showMessage(error.message); if (mode === 'signup') showMessage('Onay e-postanı kontrol et; ardından giriş yap.'); else boot(); }
function showMessage(x) { document.querySelector('#authMessage').textContent = x; }
async function boot() { if (!configured()) return; const { data: { user } } = await db().auth.getUser(); if (!user) return; hideAuth(); document.querySelector('#marketing').classList.add('hidden'); document.querySelector('#dashboard').classList.remove('hidden'); document.querySelector('#accountEmail').textContent = user.email; const { data, error } = await db().from('sites').select('*').order('created_at', { ascending: false }); if (!error) renderSites(data); }
function renderSites(items) { const area = document.querySelector('#sites'); if (!items.length) { area.innerHTML = '<div class="empty"><b>Henüz bir siten yok.</b><br><br>İlk siteni oluşturarak başlayalım.</div>'; return; } area.innerHTML = items.map(x => `<article class="site-card"><div class="site-shot"><div class="shot-title">${escapeHTML(x.name)}</div></div><div class="site-info"><b>${escapeHTML(x.name)}</b><small>${x.template} · ${x.published ? 'Yayında' : 'Taslak'}</small><div class="site-actions"><button class="primary" onclick="editSite('${x.id}')">Düzenle</button><button class="ghost" onclick="editSite('${x.id}')">Önizle</button></div></div></article>`).join(''); }
function editSite(id) { location.href = `editor.html?id=${encodeURIComponent(id)}`; }
function showNewSite() { document.querySelector('#newModal').classList.remove('hidden'); }
function hideNewSite() { document.querySelector('#newModal').classList.add('hidden'); }
function pickTemplate(el) { document.querySelectorAll('.template').forEach(x => x.classList.remove('selected')); el.classList.add('selected'); selectedTemplate = el.dataset.template; }
async function createSite(e) { e.preventDefault(); if (!configured()) return; const name = document.querySelector('#siteName').value.trim(); const content = { headline: name, subtitle: 'Kendini ve işini dünyaya anlat.', button: 'Keşfet', accent: '#d6ff4d', blocks: [] }; const { error } = await db().from('sites').insert({ name, template: selectedTemplate, content }); if (error) return alert(error.message); hideNewSite(); e.target.reset(); boot(); }
function escapeHTML(v) { const d = document.createElement('div'); d.textContent = v; return d.innerHTML; }
if (configured()) boot();
