let mode='login', selectedTemplate='Portföy';
const configured=()=>window.KUR_CONFIG && !window.KUR_CONFIG.supabaseUrl.startsWith('SUPABASE_');
const db=()=>window.supabase.createClient(KUR_CONFIG.supabaseUrl,KUR_CONFIG.supabaseAnonKey);
function showAuth(next){mode=next;document.querySelector('#authModal').classList.remove('hidden');renderAuth()}
function hideAuth(){document.querySelector('#authModal').classList.add('hidden')}
function toggleAuth(){mode=mode==='login'?'signup':'login';renderAuth()}
function renderAuth(){let sign=mode==='signup';document.querySelector('#authTitle').textContent=sign?'Hemen başla':'Hoş geldin';document.querySelector('#authHelp').textContent=sign?'İlk siteni birkaç dakika içinde oluştur.':'Paneline erişmek için giriş yap.';document.querySelector('#authSubmit').textContent=sign?'Ücretsiz hesap oluştur':'Giriş yap';document.querySelector('#switchText').textContent=sign?'Zaten hesabın var mı? ':'Hesabın yok mu? ';document.querySelector('#switchAuth').textContent=sign?'Giriş yap':'Ücretsiz kayıt ol';document.querySelector('#authMessage').textContent=''}
async function submitAuth(e){e.preventDefault();if(!configured()){showMessage('Canlı üyelik için önce config.js dosyasına Supabase bilgilerini ekleyin.');return}const email=document.querySelector('#email').value,password=document.querySelector('#password').value;const client=db();const {error}=mode==='signup'?await client.auth.signUp({email,password}):await client.auth.signInWithPassword({email,password});if(error)return showMessage(error.message);if(mode==='signup')showMessage('Onay e-postanı kontrol et; ardından giriş yap.');else await boot()}
function showMessage(x){document.querySelector('#authMessage').textContent=x}
async function boot(){if(!configured())return;const client=db();const {data:{user}}=await client.auth.getUser();if(!user)return;hideAuth();document.querySelector('#marketing').classList.add('hidden');document.querySelector('#dashboard').classList.remove('hidden');document.querySelector('#accountEmail').textContent=user.email;const {data,error}=await client.from('sites').select('*').order('created_at',{ascending:false});if(error)return;renderSites(data)}
function renderSites(items){let area=document.querySelector('#sites');if(!items.length){area.innerHTML='<div class="empty"><b>Henüz bir siten yok.</b><br><br>İlk siteni oluşturarak başlayalım.</div>';return}area.innerHTML=items.map(x=>`<article class="site-card"><div class="site-shot"><div class="shot-title">${escapeHTML(x.name)}</div></div><div class="site-info"><b>${escapeHTML(x.name)}</b><small>${x.template} · Taslak</small><div class="site-actions"><button class="primary" onclick="alert(\'Düzenleyici ekranı sıradaki geliştirme adımı.\')">Düzenle</button><button class="ghost" onclick="alert(\'Yayınlama ayarları yakında burada.\')">Yayınla</button></div></div></article>`).join('')}
function showNewSite(){document.querySelector('#newModal').classList.remove('hidden')}function hideNewSite(){document.querySelector('#newModal').classList.add('hidden')}
function pickTemplate(el){document.querySelectorAll('.template').forEach(x=>x.classList.remove('selected'));el.classList.add('selected');selectedTemplate=el.dataset.template}
async function createSite(e){e.preventDefault();if(!configured())return;const client=db();const name=document.querySelector('#siteName').value.trim();const {error}=await client.from('sites').insert({name,template:selectedTemplate});if(error){alert(error.message);return}hideNewSite();e.target.reset();await boot()}
function escapeHTML(v){const d=document.createElement('div');d.textContent=v;return d.innerHTML}
if(configured())boot();
