const client = window.supabase.createClient(KUR_CONFIG.supabaseUrl, KUR_CONFIG.supabaseAnonKey);
const siteId = new URLSearchParams(location.search).get('id');
let site, content = { headline: 'Yeni siten', subtitle: 'Kendini ve işini dünyaya anlat.', button: 'Keşfet', accent: '#d6ff4d', blocks: [] };
const esc = v => { const d = document.createElement('div'); d.textContent = v || ''; return d.innerHTML; };
async function load() { if (!siteId) return location.href = 'index.html'; const { data: { user } } = await client.auth.getUser(); if (!user) return location.href = 'index.html'; const { data, error } = await client.from('sites').select('*').eq('id', siteId).single(); if (error || !data) return location.href = 'index.html'; site = data; content = { ...content, ...(data.content || {}) }; if (!Array.isArray(content.blocks)) content.blocks = []; document.querySelector('#siteName').textContent = site.name; document.querySelector('#siteTitle').value = site.name; document.querySelector('#templateName').textContent = `${site.template} şablonu`; ['headline','subtitle','accent'].forEach(id => document.querySelector('#' + id).value = content[id]); document.querySelector('#buttonText').value = content.button; syncPreview(); }
function syncPreview() { site.name = document.querySelector('#siteTitle').value.trim() || 'Yeni siten'; content.headline = document.querySelector('#headline').value; content.subtitle = document.querySelector('#subtitle').value; content.button = document.querySelector('#buttonText').value; content.accent = document.querySelector('#accent').value; document.querySelector('#siteName').textContent = site.name; renderEditor(true); }
function renderEditor(showControls) { document.querySelector('#colorValue').textContent = content.accent; const extras = content.blocks.map((b, i) => b.type === 'image' ? `<section class="page-block image-block"><img src="${esc(b.imageUrl || '')}" alt="${esc(b.title)}"><h2>${esc(b.title)}</h2><p>${esc(b.text)}</p><button class="remove" onclick="removeBlock(${i})">Bölümü sil</button></section>` : `<section class="page-block ${b.type === 'quote' ? 'quote' : ''}"><h2>${esc(b.title)}</h2><p>${esc(b.text)}</p><button class="remove" onclick="removeBlock(${i})">Bölümü sil</button></section>`).join(''); document.querySelector('#preview').style.setProperty('--accent', content.accent); document.querySelector('#preview').innerHTML = `<header class="page-nav"><b>${esc(site.name).toUpperCase()}</b><span>Hakkında　İletişim</span></header><section class="hero"><h1>${esc(content.headline)}</h1><p>${esc(content.subtitle)}</p><button>${esc(content.button)}</button></section>${extras || '<div class="empty-preview">Sol panelden içerik bölümü ekleyerek sayfanı zenginleştir.</div>'}`; document.querySelector('#blockList').innerHTML = content.blocks.length ? content.blocks.map((b, i) => `<div class="block-item">${i + 1}. ${esc(b.title)}</div>`).join('') : '<div class="sub">Henüz ek bölüm yok.</div>'; if (showControls) document.querySelector('#blockControls').innerHTML = content.blocks.map((b, i) => `<div class="block-editor"><h3>${i + 1}. bölüm <button class="move" onclick="moveBlock(${i},-1)">↑</button><button class="move" onclick="moveBlock(${i},1)">↓</button></h3><label class="field">Başlık</label><input value="${esc(b.title)}" oninput="updateBlock(${i},'title',this.value)"><label class="field">Metin</label><textarea rows="3" oninput="updateBlock(${i},'text',this.value)">${esc(b.text)}</textarea>${b.type === 'image' ? `<label class="field">Görsel bağlantısı</label><input value="${esc(b.imageUrl || '')}" placeholder="https://..." oninput="updateBlock(${i},'imageUrl',this.value)">` : ''}</div>`).join(''); }
function addBlock(type) { const labels = { text: ['Hakkımızda', 'Buraya hikâyeni, hizmetini veya projen hakkında kısa bir açıklama ekle.'], image: ['İlham veren işler', 'Bu görselin altına kısa bir açıklama ekle.'], quote: ['İyi fikirler büyümeyi hak eder.', 'Markanı anlatan güçlü bir mesaj ekle.'], contact: ['İletişime geç', 'E-posta adresini veya sosyal medya hesabını burada paylaş.'] }; const [title, text] = labels[type]; content.blocks.push({ type, title, text, imageUrl: type === 'image' ? 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=80' : '' }); syncPreview(); }
function removeBlock(i) { content.blocks.splice(i, 1); syncPreview(); }
function updateBlock(i, key, value) { content.blocks[i][key] = value; renderEditor(false); }
function moveBlock(i, direction) { const target = i + direction; if (target < 0 || target >= content.blocks.length) return; [content.blocks[i], content.blocks[target]] = [content.blocks[target], content.blocks[i]]; syncPreview(); }
async function saveSite() { document.querySelector('#status').textContent = 'Kaydediliyor…'; const { error } = await client.from('sites').update({ name: site.name, content }).eq('id', siteId); document.querySelector('#status').textContent = error ? 'Kaydedilemedi' : '✓ Kaydedildi'; if (error) alert(error.message); }
load();
